// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const isTest = process.env["NODE_ENV"] === "test";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seeds/index.ts",
  },
  datasource: {
    url: !isTest
      ? process.env["DATABASE_URL"]
      : process.env["DATABASE_URL_TEST"],
  },
});
